r2e2/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
	url(r'^/login/$', views.user_login, name='login'),
)

r2e2/r2e2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from users import views
from rooms import views as views1
from reservations import views as views2


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'r2e2.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls')),
    # url(r'^rooms/', include('rooms.urls')),
    # url(r'^reservations/', include('reservations.urls')),
    
    
)



# urlpatterns = patterns('',

#     url(r'^admin/', include(admin.site.urls)),
#     url(r'^login/$', views.user_login, name='login'),
#     url(r'^logout/$', views.user_logout, name='logout'),
#     #url(r'^home/request_details/$', myviews.request_detail, name='add_request'),
#    url(r'^login/reservations/reservation_lists/$', views2.reservation_list, name='add_request'),
#    url(r'^reservations/reservation_lists1/$', views2.reservation_list1, name='add_request1'),
#    url(r'^users/user_lists/$', views.user_list, name='user_list'),  
#     url(r'^users/add_user/$', views.register, name='register'),
#     url(r'^reservations/add_reservation/$', views2.add_reserve, name='reservation'), 
#     url(r'rooms/add_room/$', views1.add_room, name='room'),
#     url(r'reservations/request_details/(?P<reserve_id>\w+)/$', views2.request_detail, name='request_detail')
# )

r2e2/rooms/urls.py
from django.conf.urls import patterns, url
from rooms import views

urlpatterns = patterns('',
	 url(r'^add_room/$', views.add_room, name='add_room'),
)

r2e2/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	O = 'Organization'
	F = 'Faculty'
	G = 'Guest'
	SA = 'System Administrator'
	BA = 'Building Administrator'
	DC = 'Deparment Chair'

	User_Type_Choices = (
		(O, 'Organization'),
		(F, 'Faculty'),
		(G, 'Guest'),
		(SA, 'System Admin'),
		(BA, 'Building Admin'),
		(DC, 'Dept Chair'),
	)
	
	userType = models.CharField(max_length=20, choices=User_Type_Choices, default='SA')
	priorityLevel = models.IntegerField(default=0)
	additionalProperties = models.CharField(max_length=40)

	def __unicode__(self):
		return self.user.username

r2e2/home/models.py
from django.db import models
from accounts.models import UserProfile
from django.contrib.admin.widgets import AdminTimeWidget
# Create your models here.
class Rooms(models.Model):
	roomName = models.CharField(max_length=20)
	roomType = models.CharField(max_length=20)
	roomNumber = models.IntegerField()
	#capacity = models.IntegerField()

	def __unicode__(self):
		return self.roomName

	class Meta:
		verbose_name_plural = 'Rooms'

#class Events(models.Model):
	#eventName = models.CharField(max_length=20)
	#eventType = models.CharField(max_length=20)
	#startTime = models.TimeField()
	#endTime = models.TimeField()
	#date = models.DateField()
	#created_by = models.ForeignKey(UserProfile, related_name='events_created_by')
	#created_by = models.CharField(max_length=30);
	#approved_by = models.ForeignKey(UserProfile, related_name='events_approved_by')
	#approvalStatus = models.CharField(max_length=30)

	#def __unicode__(self):
		#return self.eventName

	#class Meta:
		#verbose_name_plural = 'Events'

#class Schedules(models.Model):
	#startTime = models.TimeField()
	#endTime = models.TimeField()
	#date = models.DateField()
	#event = models.ForeignKey(Events)

	#class Meta:
		#verbose_name_plural = 'Schedules'

class Requests(models.Model):
	#event = models.ForeignKey(Events)
	#schedule = models.ForeignKey(Schedules)
	eventName = models.CharField(max_length=30,null=True, blank=True)
	# eventType = models.CharField(max_length=30,null=True, blank=True)
	partiNumber = models.IntegerField(null=True, blank=True)
	room = models.ForeignKey(Rooms)
	startTime = models.TimeField(null=True, blank=True)
	endTime = models.TimeField(null=True, blank=True)
	date = models.DateField(null=True, blank=True)
	purpose = models.CharField(max_length=50,null=True, blank=True)
	requestedBy = models.ForeignKey(UserProfile, related_name='requests_requestedBy',null=True, blank=True)
	approvedBy = models.ForeignKey(UserProfile,related_name='requests_adminApproved',null=True, blank=True)
	tag = models.IntegerField(null=True, blank=True)
	# user_type = models.ForeignKey(UserProfile,null=True,blank=True)
	# req = models.CharField(max_length=50,null=True, blank=True)
	#adminApproved = models.ForeignKey(UserProfile, related_name='requests_adminApproved')
	#chairApproves = models.ForeignKey(UserProfile, related_name='requests_chairApproves')
 
	def __unicode__(self):
		return self.eventName

	class Meta:
		verbose_name_plural = 'Requests'

r2e2/rooms/models.py
from django.db import models

# Create your models here.
class Rooms(models.Model):
	roomName = models.CharField(max_length=20)
	roomType = models.CharField(max_length=20)
	roomNumber = models.IntegerField()
	#capacity = models.IntegerField()

	def __unicode__(self):
		return self.roomName

	class Meta:
		verbose_name_plural = 'Rooms'

r2e2/accounts/forms.py
from django.http import HttpResponseRedirect
from django import forms
from django.contrib.auth.models import User
from accounts.models import UserProfile
from home.models import Requests,Rooms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('additionalProperties','userType',)


#class EventForm(forms.ModelForm):

   # class Meta:
	#model = Events
	#fields = ('eventName', 'eventType',)

class RoomForm(forms.ModelForm):
	
    class Meta:
		model = Rooms
		fields = ('roomName','roomNumber')

class ReserveForm(forms.ModelForm):

    	class Meta:
			model = Requests
			fields = ('eventName','partiNumber','room','startTime','endTime','date','purpose')


		
#class ScheduleForm(forms.ModelForm):

    #class Meta:
	#model = Schedules
	#fields = ('startTime', 'endTime', 'date',)
	

r2e2/rooms/forms.py
from django import forms
from rooms.models import Rooms

class RoomForm(forms.ModelForm):
	
    class Meta:
		model = Rooms
		fields = ('roomName','roomNumber')

r2e2/accounts/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from accounts.forms import UserForm, UserProfileForm,RoomForm,ReserveForm
from accounts.models import UserProfile
from home.models import Rooms,Requests
from home.views import reservation_list1, reservation_list

def user_login(request):
    context = RequestContext(request)

    if request.method == 'POST':
           
        username = request.POST['username']
        password = request.POST['password']
    	
        user = authenticate(username=username, password=password)
        # profile = UserProfile.objects.get(user=user)

        if user:
               
            if user.is_active:
                login(request, user)
                profile = UserProfile.objects.get(user=user)
                if profile.userType == 'System Administrator' : 
                	return HttpResponseRedirect('/home/reservation_lists/')
                else:
                    return HttpResponseRedirect('/home/reservation_lists1/')
            else:
                   
                return HttpResponse("Your account is disabled.")
        else:
                
            print "Invalid login details: {0}, {1}".format(username, password)
            # return HttpResponseRed("Invalid login details supplied.")
            return render_to_response('accounts/login1.html', {}, context)
    else:
        
        return render_to_response('accounts/login.html', {}, context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/login/')
	
@login_required
def register(request):
    registered = False
    profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

	    profile = profile_form.save(commit=False)
	    profile.user = user

	    profile.save()
            registered = True

        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'accounts/reg.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered, 'profile': profile,} )

@login_required
def add_reserve(request):
    registered = False
    profile = UserProfile.objects.get(user=request.user)
    rooms = Rooms.objects.all()
    user = request.user
    if request.method == 'POST':
        #event_form = EventForm(data=request.POST)
	#room_form = RoomForm(data=request.POST)
	#schedule_form = ScheduleForm(data=request.POST)
	reserve_form = ReserveForm(data=request.POST)

        #if event_form.is_valid() and room_form.is_valid() and schedule_form.is_valid():
	if reserve_form.is_valid():
            reserve = reserve_form.save()
            reserve.requestedBy = profile
            reserve.tag = 0
            reserve.save()
	   # event.created_by = profile
	   # event.approvalStatus = "AA"
           # event.save()
	   # room = room_form.save()
	   # room.save()

	   # schedule = schedule_form.save()
	   # schedule.save()

            registered = True

            if user.is_superuser:

                return HttpResponseRedirect('/home/reservation_lists/')
            else:
                return HttpResponseRedirect('/home/reservation_lists1/')

        else:
	    print reserve_form.errors
            # print event_form.errors, room_form.errors, schedule_form.errors
    else:
        # event_form = EventForm()
        # room_form = RoomForm()
	# schedule_form = ScheduleForm()
	reserve_form = ReserveForm()

    return render(request,
            'accounts/reserve.html',
	     {'reserve_form': reserve_form,'registered':registered, 'rooms':rooms, 'profile':profile,})

@login_required
def add_room(request):
    registered = False
    profile = UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        room_form = RoomForm(data=request.POST)


        if room_form.is_valid():
            room = room_form.save()
            room.save()

	    
            registered = True
            return reservation_list(request)

        else:
            print room_form.error
    else:
        room_form = RoomForm()
        #profile_form = UserProfileForm()

    return render(request,
            'accounts/room.html',
            {'room_form': room_form,'registered': registered, 'profile': profile} )

r2e2/rooms/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from users.models import UserProfile
from rooms.forms import RoomForm
from reservations.views import reservation_list

# Create your views here.

@login_required
def add_room(request):
    registered = False
    profile = UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        room_form = RoomForm(data=request.POST)


        if room_form.is_valid():
            room = room_form.save()
            room.save()

	    
            registered = True
            return reservation_list(request)

        else:
            print room_form.error
    else:
        room_form = RoomForm()
        #profile_form = UserProfileForm()

    return render(request,
            'rooms/room.html',
            {'room_form': room_form,'registered': registered, 'profile': profile} )

r2e2/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html>
   <head>
      <title> R2E2 || Homepage </title>
      <link type = "text/css" rel = "stylesheet" href = "{% static "login.css" %}">
      <link type = "text/css" rel = "stylesheet" href = "{% static "flat-ui.css" %}">
   </head>
   <body>

   		<div class = "announcement-section">
   			<p id = "announcement-header"> Announcement </p>
   			<p class = "announcement-p"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
   			<p class = "announcement-p"> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
   		</div>

      	<div id = "system-name">
      		<h3> R2E2 </h3>
      		<h6> - Room Reservation System Itu - </h6>
      		<p> Sign in </p>
	      	<div id = "username">
		      	<div class="col-xs-3">
		          <div class="form-group">
		          	<form id="login_form" method="post" action="/login/">
            		{% csrf_token %} 
		            <input type="text" name="username" value="" placeholder="Username" class="form-control" />
		          </div>
		        </div>
	        </div>
	        <div id = "password">
		      	<div class="col-xs-3">
		          <div class="form-group">
		          	 
		            <input type="password" name="password" value="" placeholder="Password" class="form-control"/>
		          </div>
		        </div>
	        </div>

          <div id= "log-in-button">
	        <a class="btn btn-primary btn-lg btn-block">
             <input type="submit" value="Log in" /></a>
            </div>
            </form>

		</div>

        <div class = "how-to-reserve">
        	<img src = "{% static "HowTo Reserve.png" %}">
        </div>
   </body>
</html>

r2e2/templates/accounts/login1.html
<!DOCTYPE html>
{% load static %}
<html>
   <head>
      <title> R2E2 || Homepage </title>
      <link type = "text/css" rel = "stylesheet" href = "{% static "login.css" %}">
      <link type = "text/css" rel = "stylesheet" href = "{% static "flat-ui.css" %}">
   </head>
   <body>

   		<div class = "announcement-section">
   			<p id = "announcement-header"> Announcement </p>
   			<p class = "announcement-p"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
   			<p class = "announcement-p"> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
   		</div>

      	<div id = "system-name">
      		<h3> R2E2 </h3>
      		<h6> - Room Reservation System Itu - </h6>
      		<!-- <p> Sign in </p> -->
          <p style="color:red"> Invalid username/password </p>
	      	<div id = "username">
		      	<div class="col-xs-3">
		          <div class="form-group">
		          	<form id="login_form" method="post" action="/login/">
            		{% csrf_token %} 
		            <input type="text" name="username" value="" placeholder="Username" class="form-control" />
		          </div>
		        </div>
	        </div>
	        <div id = "password">
		      	<div class="col-xs-3">
		          <div class="form-group">
		          	 
		            <input type="password" name="password" value="" placeholder="Password" class="form-control"/>
		          </div>
		        </div>
	        </div>

          <div id= "log-in-button">
	        <a class="btn btn-primary btn-lg btn-block">
             <input type="submit" value="Log in" /></a>
            </div>
            </form>

		</div>

        <div class = "how-to-reserve">
        	<img src = "{% static "HowTo Reserve.png" %}">
        </div>
   </body>
</html>

r2e2/templates/accounts/reg.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> R2E2 || Room Reservation Request </title>
      <link type = "text/css" rel = "stylesheet" href = "{% static "boxui.css" %}">
   </head>

    <body>
        <div id = "header">
         <p id = "headerTitle">R2E2 : Room Reservation Itu!</p>
         <p id = "headerSub">UP Department of Computer Science</p>
      </div>

      <div id = "main_left">
         <a href = "">
            <div id = "user">
               <p id = "orgname">{{user.username}}</p>
               <p id = "type">{{profile.userType}}</p>
            </div>
         </a>
                <a href = "/home/user_lists/" class = "choice">
            <div><p>List of Users</p></div>
         </a>
          <a href = "/home/reservation_lists/" class = "choice">
            <div><p>List of Reservations</p></div>
         </a>
         <a href = "/home/add_reservation/" class = "choice">
            <div><p>Reserve Rooms</p></div>
         </a>
        <a href = "/home/add_user/" class = "choice">
            <div><p>Add User</p></div>
         </a>
         <a href = "/home/add_room/" class = "choice">
            <div><p>Add Rooms</p></div>
         </a>
        <a href = "/login/" class = "choice">
            <div><p>Log Out</p></div>
         </a>
      </div>
      <div id = "main_right">
         <div id = "appForm"><p>USER REGISTRATION</p>
      </div>
         <form id="user_form" method="post" 
                enctype="multipart/for`m-data">

            {% csrf_token %}

            <div class = "division">
            <p class = "description"><label for="id_username">USERNAME</label> </p><input id="id_username" maxlength="30" name="username" type="text" class = "textInput"></div>
            <div class = "division">
            <p class = "description"><label for="id_email">EMAIL ADDRESS</label></p> <input id="id_email" maxlength="75" name="email" type="email" class = "textInput"></div>
            <div class = "division">
            <p class = "description"><label for="id_password">PASSWORD</label></p> <input id="id_password" name="password" type="password" class = "textInput"></div>
            <div class = "division">
            <p class = "description"><label for="id_additionalProperties">ADDITIONAL PROPERTIES</label></p> <input id="id_additionalProperties" maxlength="40" name="additionalProperties" type="text" class = "textInput"></div>
            <div class = "division">
            <p class = "description"><label for="id_userType">USER TYPE</label> </p><select id="id_userType" name="userType" class = "dropDown textInput">
            <option value="Organization">Organization</option>
            <option value="Faculty">Faculty</option>
            <option value="Guest">Guest</option>
            <option value="System Administrator">System Admin</option>
            <option value="Building Administrator">Building Admin</option>
            <option value="Deparment Chair">Dept Chair</option>
            </select></div>

            <!-- Provide a button to click to submit the form. -->
            <div class = "division">
            <input type="submit" name="submit" value="Register" />
            </div>
        </form>
    </body>
</html>

r2e2/templates/accounts/reserve.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> R2E2 || Room Reservation Request </title>
      <link type = "text/css" rel = "stylesheet" href = "{% static "boxui.css" %}">
   </head>

    <body>
        <div id = "header">
         <p id = "headerTitle">R2E2 : Room Reservation Itu!</p>
         <p id = "headerSub">UP Department of Computer Science</p>
      </div>

      <div id = "main_left">
         <a href = "">
            <div id = "user">
               <p id = "orgname">{{user.username}}</p>
               <p id = "type">{{profile.userType}}</p>
            </div>
         </a>
        {% if profile.userType != 'System Administrator' %}
             <a href = "/home/reservation_lists1/" class = "choice">
                <div><p>View Reserve Rooms</p></div>
             </a>
        {% endif %}
         {% if profile.userType = 'System Administrator' %}
                <a href = "/home/user_lists/" class = "choice">
            <div><p>List of Users</p></div>
             </a>
              <a href = "/home/reservation_lists/" class = "choice">
                <div><p>List of Reservations</p></div>
             </a>
         {% endif %}
         <a href = "/home/add_reservation/" class = "choice">
            <div><p>Reserve Rooms</p></div>
         </a>
    {% if profile.userType = 'System Administrator' %}
        <a href = "/home/add_user/" class = "choice">
                <div><p>Add User</p></div>
             </a>
        <a href = "/home/add_room/" class = "choice">
                <div><p>Add Rooms</p></div>
             </a>
    {% endif %}
  <a href = "/login/" class = "choice">
            <div><p>Log Out</p></div>
         </a>
      </div>
      <div id = "main_right">
         <div id = "appForm"><p>APPLICATION FORM FOR THE USE OF DCS ROOMS</p></div>
        <form id="reserve_form" method="post" action="/home/add_reservation/" enctype="multipart/form-data">

           {% csrf_token %}
            <div class = "division">
            <p class = "description">NAME OF EVENT<label for="id_eventName"></label></p>
            <input id="id_eventName" maxlength="30" name="eventName" type="text" class = "textInput">
            </div>
            <div class = "division">
            <p class = "description">NUMBER OF PARTICIPANTS<label for="id_partiNumber"></label></p><input id="id_partiNumber" name="partiNumber" type="number" class = "time_participants textInput">
            </div>
            <div class = "division">
            <p class = "description">ROOM TO BE USED<label for="id_room"></label></p><select id="id_room" name="room" class = "dropDown textInput">
            <option value="" selected="selected">---------</option>
            {% for room in rooms %}
            <option value="{{room.id}}">{{room}}</option>
            {% endfor %}
            </select>
            </div>
            <div class = "division">
            <p class = "description"><label for="id_startTime">TIME</label> </p><input id="id_startTime" name="startTime" type="time" class = "time_participants textInput1">
            <p style = "font-size: 1em; font-family: Nexa Bold; color: black; display: inline-block">to</p>
            <label for="id_endTime"></label><input id="id_endTime" name="endTime" type="time" class = "time_participants textInput1" style="display: inline-block"> </div>
            <div class = "division">
            <p class = "description"><label for="id_date">DATE</label></p><input id="id_date" name="date" type="date" class = "textInput"></div>
            <div class = "division">
            <p class = "description"><label for="id_purpose">PURPOSE</label></p><input id="id_purpose" maxlength="50" name="purpose" type="text" class = "textInput"> </div>
            <!---->
        <!---->

            <!-- Provide a button to click to submit the form. -->
            <div class = "division">
            <p class = "description"> <input type="submit" name="submit" value="Add Reservation"> </p> </div>
        </form>
    </body>
</html>

r2e2/templates/accounts/room.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> R2E2 || Room Reservation Request </title>
      <link type = "text/css" rel = "stylesheet" href = "{% static "boxui.css" %}">
   </head>

    <body>
        <div id = "header">
         <p id = "headerTitle">R2E2 : Room Reservation Itu!</p>
         <p id = "headerSub">UP Department of Computer Science</p>
      </div>

      <div id = "main_left">
         <a href = "">
            <div id = "user">
               <p id = "orgname">{{user.username}}</p>
               <p id = "type">{{profile.userType}}</p>
            </div>
         </a>
                <a href = "/home/user_lists/" class = "choice">
            <div><p>List of Users</p></div>
         </a>
          <a href = "/home/reservation_lists/" class = "choice">
            <div><p>List of Reservations</p></div>
         </a>
         <a href = "/home/add_reservation/" class = "choice">
            <div><p>Reserve Rooms</p></div>
         </a>
    <a href = "/home/add_user/" class = "choice">
            <div><p>Add User</p></div>
         </a>
    <a href = "/home/add_room/" class = "choice">
            <div><p>Add Rooms</p></div>
         </a>
  <a href = "/login/" class = "choice">
            <div><p>Log Out</p></div>
         </a>
      </div>
      <div id = "main_right">
         <div id = "appForm"><p>ADDITION OF ROOM</p></div>
           <form id="room_form" method="post"  enctype="multipart/form-data">

          {% csrf_token %}
            <div class = "division">
            <p class = "description"><label for="id_roomName">ROOM NAME</label></p> <input id="id_roomName" maxlength="20" name="roomName" type="text" class = "textInput"></div>
            <div class = "division">
            <p class = "description"><label for="id_roomNumber">ROOM NUMBER</label></p> <input id="id_roomNumber" name="roomNumber" type="number" class = "time_participants textInput"></div>
            <div class = "division">
            <input type="submit" name="submit" value="Add Room"></div>
        </form>
    </body>
</html>